unit TestVulkanTestMF;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vulkan, System.Variants, Data.DB, Datasnap.Provider,
  Datasnap.DBClient, Winapi.Windows, Vcl.Dialogs, VulkanTestMF, Vcl.Forms,
  Data.Win.ADODB, Vcl.Controls, System.Classes, System.SysUtils, Winapi.Messages,
  Vulkan_WindowVCL, VulkanTestDM, Vcl.Graphics, Vulkan_Components, Vcl.StdCtrls,
  Vcl.Buttons, Vcl.ComCtrls;

implementation

initialization
  // Register any test cases with the test runner
  
end.

