unit TestVulkanTestMF;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vulkan, System.Variants, Data.DB, Datasnap.Provider,
  Datasnap.DBClient, Winapi.Windows, Vcl.Dialogs, VulkanTestMF, Vcl.Forms,
  Data.Win.ADODB, Vcl.Controls, System.Classes, System.SysUtils, Winapi.Messages,
  Vulkan_WindowVCL,  Vcl.Graphics, Vulkan_Components, Vcl.StdCtrls,
  Vcl.Buttons, Vcl.ComCtrls, Vcl.ExtCtrls, PasVulkan.Math,
  Vulkan_Components_Lookups;

type
  // Test methods for class TForm8

  TestTForm8 = class(TTestCase)
  strict private
    FForm8: TForm8;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestButton1Click;
    procedure TestButton2Click;
    procedure TestButton4Click;
    procedure TestButton3Click;
    procedure TestButton5Click;
    procedure TestBitBtn1Click;
    procedure TestBitBtn3Click;
    procedure TestBitBtn2Click;
    procedure TestBitBtn4Click;
    procedure TestButton6Click;
    procedure TestvgWindowLink1RenderPassBuild;
    procedure TestButton7Click;
  end;

implementation

procedure TestTForm8.SetUp;
begin
  FForm8 := TForm8.Create;
end;

procedure TestTForm8.TearDown;
begin
  FForm8.Free;
  FForm8 := nil;
end;

procedure TestTForm8.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button1Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton2Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button2Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton4Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button4Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton3Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button3Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton5Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button5Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestBitBtn1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.BitBtn1Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestBitBtn3Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.BitBtn3Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestBitBtn2Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.BitBtn2Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestBitBtn4Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.BitBtn4Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton6Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button6Click(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestvgWindowLink1RenderPassBuild;
var
  Sender: TvgRenderPass;
begin
  // TODO: Setup method call parameters
  FForm8.vgWindowLink1RenderPassBuild(Sender);
  // TODO: Validate method results
end;

procedure TestTForm8.TestButton7Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FForm8.Button7Click(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  
end.

