// ------------------------------------------------------
// VERTEX SHADER - generated by TvgShaderBuilder
// Pipeline : TvgGraphicPipeline_Inst_1
// ------------------------------------------------------

#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_shader_explicit_arithmetic_types_float64 : enable
#extension GL_ARB_gpu_shader_fp64 : enable


// --- Specialisation constants ---
layout(constant_id = 0) const bool USE_OBJECTID = true;
layout(constant_id = 1) const bool USE_DOUBLE = true;


// --- SET 0 - Global resources ---
layout(set = 0, binding = 0, std140) uniform ModelViewProjBlock {
    dmat4 value;
} ModelViewProj;


// --- SET 1 - Object-store resources ---


// --- Per-vertex inputs ---
layout(location = 0) in vec3 inPosition;  // per-vertex
layout(location = 1) in vec4 inColor;  // per-vertex
layout(location = 2) in vec2 inTexCoord;  // per-vertex
layout(location = 3) in uvec2 inObjID; // per-instance


// --- Vertex ? fragment interpolants (out) ---
layout(location = 0) out vec4 fragColor0;
layout(location = 1) out vec2 fragTexCoord1;
layout(location = 2) flat out uvec2 fragObjectID2;


void main()
{
    gl_Position = vec4(ModelViewProj.value * dvec4(vec4(inPosition, 1.0)));

    // Pass-through interpolants
    fragColor0 = inColor;
    fragTexCoord1 = inTexCoord;
    fragObjectID2 = inObjID;
}
