// ------------------------------------------------------
// FRAGMENT SHADER - generated by TvgShaderBuilder
// Pipeline : TvgGraphicPipeline_Inst_1
// ------------------------------------------------------

#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : enable


// --- Specialisation constants ---
layout(constant_id = 0) const bool USE_OBJECTID = true;

// ObjectID writes must occur only after depth tests pass
layout(early_fragment_tests) in;


// --- SET 0 - Global resources ---
layout(set = 0, binding = 0, std140) uniform ModelViewProjBlock {
    dmat4 value;
} ModelViewProj;
//   
// Storage buffer target for ObjectID (selection)
// SET = 0  Binding = 1
layout(set = 0, binding = 1, std430) buffer outObjectIDBufferBlock {
    uvec2 values[];
} outObjectIDBuffer[64];


// --- SET 1 - Object-store resources ---
layout(set = 1, binding = 0) uniform sampler2D SimpleTexture;


// --- Push constants ---
layout(push_constant) uniform PushConstant_2UI
{
    ivec2 value;
} inScreenSize_00;


// --- Fragment inputs (interpolated from vertex stage) ---
layout(location = 0) in vec4 fragColor0;
layout(location = 1) in vec2 fragTexCoord1;
layout(location = 2) flat in uvec2 fragObjectID2;


// --- Fragment outputs ---
layout(location = 0) out vec4 outColor;


void main()
{
    outColor = texture(SimpleTexture, fragTexCoord1);

    if (USE_OBJECTID) {
        ivec2 screenCoord = ivec2(gl_FragCoord.xy);
        ivec2 screenSize  = ivec2(inScreenSize_00.value);
        if (screenCoord.x >= 0 && screenCoord.y >= 0 &&
            screenCoord.x < screenSize.x && screenCoord.y < screenSize.y)
        {
            uint screenIndex = uint(screenCoord.y * screenSize.x + screenCoord.x);
            outObjectIDBuffer[nonuniformEXT(0)].values[screenIndex] = fragObjectID2.xy;
        }
    }
}